Refactor export to exportSchedule and update DG
AY2122S2-CS2103T-W09-1/tp pull request #110
Opened 2022-03-24 13:26 UTC by hanqinilnix

2022-03-25 03:10 UTC, vishandi requested changes

2022-03-25 03:10 UTC, vishandi commented on docs/diagrams/ExportScheduleActivityDiagram.puml
> +@enduml
Is this activity diagram really necessary? As it is really simple and I think the developers who read the DG can understand it only by its description without the diagram.

2022-03-26 09:38 UTC, hanqinilnix commented on docs/DeveloperGuide.md
> +  * Pro:
There is only one pro, therefore singular.

2022-03-29 15:16 UTC, vishandi commented
LGTM

2022-03-29 15:16 UTC, merged