Fix viewschedule bugs
AY2122S2-CS2103T-W09-1/tp pull request #190
Opened 2022-04-06 16:20 UTC by vishandi

2022-04-08 05:14 UTC, tyanhan requested changes

2022-04-08 05:14 UTC, tyanhan commented on src/main/java/seedu/address/model/schedule/Event.java
> +     * @param date
Line 254 can remove?

2022-04-08 05:14 UTC, tyanhan commented on src/main/java/seedu/address/model/schedule/Event.java
>       * @return an Event for that particular date.
Need to update JavaDocs for this

2022-04-08 11:06 UTC, tyanhan commented on src/main/java/seedu/address/model/schedule/Event.java
> +     * Returns the next Event of the next time this event will occur, if it is a recurring event.
Returns the next recurrence of this Event

2022-04-08 14:50 UTC, hanqinilnix commented
Looks good to me

2022-04-08 14:52 UTC, hanqinilnix commented on src/main/java/seedu/address/model/schedule/Event.java
> +        if (date.isBefore(getDate()) || !willDateCollide(date)) {
Perhaps you can add comments before the if statements to make the code more readable

2022-04-09 03:27 UTC, hanqinilnix commented
Looks good

2022-04-09 03:28 UTC, merged